# Generated by Django 5.1.4 on 2024-12-23 07:22

import django.core.validators
import registrations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Enter a valid NIC (9 digits followed by 'V'/'X' or 12 digits).", regex='^[0-9]{9}[VXvx]$|^[0-9]{12}$')])),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10, null=True)),
                ('mobile_number_1', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number with 10 to 15 digits.', regex='^\\+?[0-9]{10,15}$')])),
                ('mobile_number_2', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number with 10 to 15 digits.', regex='^\\+?[0-9]{10,15}$')])),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number with 10 to 15 digits.', regex='^\\+?[0-9]{10,15}$')])),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('working_type', models.CharField(blank=True, max_length=50, null=True)),
                ('possible_working_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('verification_type', models.CharField(blank=True, choices=[('Passport', 'Passport'), ('Driving License', 'Driving License'), ('National ID', 'National ID')], max_length=50, null=True)),
                ('verification_document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('front_side_document', models.ImageField(blank=True, null=True, upload_to=registrations.models.Application.upload_to_front)),
                ('back_side_document', models.ImageField(blank=True, null=True, upload_to=registrations.models.Application.upload_to_back)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
