# Generated by Django 5.1.4 on 2024-12-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_application_nic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='working_type',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=50, null=True),
        ),
    ]
